### ISSUE TITLE
Credit?

### ISSUE THREAD

**Issue by Rishgod** [ashwaniYDV/ashwaniYDV.github.io#1]
Hey man, I've no problem with you getting inspired by the design but can you please mention my name at the end or better try to change the source code(you just copied the source map!! :( ) a bit, cause just changing your name looks a bit crummy, to be honest! I seriously spend days trying to understand the regex which makes it work

**Comment by ashwaniYDV** [comment]
@Rishgod I'm extremely sorry. I was awestruck bt the design. I have removed it. Sorry again.
